pagopa/idpay-reward-calculator

helm/values-dev.yaml, helm/values.yaml
Move environment independent configurations in values.yml
=> Values yaml update

helm/values.yaml, src/main/java/it/gov/pagopa/reward/dto/HpanUpdateOutcomeDTO.java, src/main/java/it/gov/pagopa/reward/dto/mapper/HpanList2HpanUpdateOutcomeDTOMapper.java, src/main/java/it/gov/pagopa/reward/dto/mapper/HpanUpdateBulk2SingleMapper.java, src/main/java/it/gov/pagopa/reward/dto/mapper/HpanUpdateEvaluateDTO2HpanInitiativeMapper.java, src/main/java/it/gov/pagopa/reward/service/ErrorNotifierService.java, src/main/java/it/gov/pagopa/reward/service/ErrorNotifierServiceImpl.java, src/main/java/it/gov/pagopa/reward/service/lookup/HpanInitiativeMediatorServiceImpl.java, src/main/java/it/gov/pagopa/reward/service/lookup/HpanInitiativesServiceImpl.java, src/main/java/it/gov/pagopa/reward/service/lookup/HpanUpdateNotifierService.java, src/main/java/it/gov/pagopa/reward/service/lookup/HpanUpdateNotifierServiceImpl.java, src/main/java/it/gov/pagopa/reward/service/lookup/ops/AddHpanServiceImpl.java, src/main/java/it/gov/pagopa/reward/service/lookup/ops/DeleteHpanServiceImpl.java, src/main/java/it/gov/pagopa/reward/utils/HpanInitiativeConstants.java, src/main/resources/application.yml, src/test/java/it/gov/pagopa/reward/BaseIntegrationTest.java, src/test/java/it/gov/pagopa/reward/dto/mapper/HpanUpdateBulk2SingleMapperTest.java, src/test/java/it/gov/pagopa/reward/dto/mapper/HpanUpdateEvaluateDTO2InitialEntityMapperTest.java, src/test/java/it/gov/pagopa/reward/event/consumer/HpanInitiaveConsumerConfigTest.java, src/test/java/it/gov/pagopa/reward/service/build/RewardRuleMediatorServiceImplTest.java, src/test/java/it/gov/pagopa/reward/service/lookup/HpanInitiativeMediatorServiceImplTest.java, src/test/java/it/gov/pagopa/reward/service/lookup/HpanInitiativesServiceImplTest.java, src/test/java/it/gov/pagopa/reward/service/lookup/ops/AddHpanServiceImplTest.java, src/test/java/it/gov/pagopa/reward/service/lookup/ops/DeleteHpanServiceImplTest.java, src/test/java/it/gov/pagopa/reward/test/fakers/HpanInitiativesFaker.java
* IREER-177 Initializing hpan update outcome to topic
* IREER-177 Added test with check into hpan-update-outcome topic
* IREER-177 Added use case test for error publishing
* IREER-177 Added helm configs
* IREER-177 change flatmap into HpanInitiativeMediatorServiceImpl
Co-authored-by: GiovanaSolorzano <gisolorz@emeal.nttdata.com>
=> Ireer-177 (#56)

src/main/resources/application.yml
* cosmosdb/mongodb idle timeout limit fixed
* cosmosdb/mongodb min pool sizes fixed
=> Fix mongo idle timeout (#61)

src/main/java/it/gov/pagopa/reward/dto/mapper/Transaction2RewardTransactionMapper.java, src/main/java/it/gov/pagopa/reward/dto/mapper/Transaction2TransactionProcessedMapper.java, src/main/java/it/gov/pagopa/reward/dto/trx/TransactionDTO.java, src/main/java/it/gov/pagopa/reward/model/TransactionProcessed.java, src/main/java/it/gov/pagopa/reward/service/reward/trx/TransactionValidatorServiceImpl.java, src/main/java/it/gov/pagopa/reward/utils/Utils.java, src/test/java/it/gov/pagopa/reward/BaseIntegrationTest.java, src/test/java/it/gov/pagopa/reward/dto/mapper/Transaction2RewardTransactionDTOMapperTest.java, src/test/java/it/gov/pagopa/reward/dto/mapper/Transaction2TransactionDroolsMapperTest.java, src/test/java/it/gov/pagopa/reward/dto/mapper/Transaction2TransactionProcessedMapperTest.java, src/test/java/it/gov/pagopa/reward/event/processor/TransactionProcessorTest.java, src/test/java/it/gov/pagopa/reward/service/reward/trx/TransactionValidatorServiceTest.java, src/test/java/it/gov/pagopa/reward/test/fakers/TransactionDTOFaker.java, src/test/java/it/gov/pagopa/reward/test/fakers/TransactionDroolsDtoFaker.java, src/test/java/it/gov/pagopa/reward/test/fakers/TransactionProcessedFaker.java, src/test/java/it/gov/pagopa/reward/utils/UtilsTest.java
* IREER-226 adding amountCents field
* added javadoc to amount field
=> IREER-226 adding amountCents field (#76)

src/main/java/it/gov/pagopa/reward/service/reward/OnboardedInitiativesServiceImpl.java, src/main/java/it/gov/pagopa/reward/service/reward/RewardContextHolderService.java, src/main/java/it/gov/pagopa/reward/service/reward/RewardContextHolderServiceImpl.java, src/main/java/it/gov/pagopa/reward/service/reward/evaluate/InitiativesEvaluatorFacadeServiceImpl.java, src/main/java/it/gov/pagopa/reward/service/reward/evaluate/UserInitiativeCountersUpdateService.java, src/main/java/it/gov/pagopa/reward/service/reward/evaluate/UserInitiativeCountersUpdateServiceImpl.java, src/main/resources/logback-spring.xml, src/test/java/it/gov/pagopa/reward/event/processor/BaseTransactionProcessorTest.java, src/test/java/it/gov/pagopa/reward/service/reward/OnboardedInitiativesServiceImplTest.java, src/test/java/it/gov/pagopa/reward/service/reward/RewardContextHolderServiceImplTest.java, src/test/java/it/gov/pagopa/reward/service/reward/evaluate/InitiativeEvaluatorFacadeServiceTest.java, src/test/java/it/gov/pagopa/reward/service/reward/evaluate/UserInitiativeCountersUpdateServiceImplTest.java
* removed blocking logic
* audit appender async
* fixed unit tests
=> Removed blocking logic (#97)

pom.xml, src/main/java/it/gov/pagopa/reward/utils/AuditUtilities.java, src/test/java/it/gov/pagopa/reward/test/utils/MemoryAppender.java, src/test/java/it/gov/pagopa/reward/utils/AuditUtilitiesTest.java
fixed reward amount print
fixed unitTests
=> refactor auditLog

pom.xml, src/main/java/it/gov/pagopa/reward/utils/AuditUtilities.java, src/test/java/it/gov/pagopa/reward/test/utils/MemoryAppender.java, src/test/java/it/gov/pagopa/reward/utils/AuditUtilitiesTest.java
* refactor auditLog fixed reward amount print
fixed unitTests
* letting log appender format message
=> refactor auditLog (#101)

src/test/java/it/gov/pagopa/common/reactive/mongo/BaseReactiveMongoRepositoryIntegrationTest.java, src/test/java/it/gov/pagopa/common/reactive/mongo/BaseReactiveMongoRepositoryTestIntegrated.java, src/test/java/it/gov/pagopa/common/redis/config/EmbeddedRedisTestConfiguration.java, src/test/java/it/gov/pagopa/common/utils/TestUtils.java
* IDP-1106 findById optimize to be run on cosmosDB
* extending coverage
=> feat: IDP-1106 findById optimize to be run on cosmosDB (#152)

src/test/java/it/gov/pagopa/common/kafka/service/ErrorNotifierServiceTest.java, src/test/java/it/gov/pagopa/common/utils/TestUtils.java
* Testing ErrorNotifierService
* relaxing unitTests
=> feat: Testing ErrorNotifierService (#155)

src/main/java/it/gov/pagopa/reward/service/commands/ops/DeleteInitiativeServiceImpl.java
**Description**
The purpose of this PR is to allign performance logs for the initiative delete.
**List of changes**
-  Modify and info logs
**Motivation and context**
**How has this been tested?**
**Types of changes**
**Checklist:**
=> fix: log info delete initiative

helm/values-prod.yaml
* fix helm chart lock
* disable prod autoscale
=> chore: disable autoscale prod (#198)

helm/values-prod.yaml
=> chore: set autoscale to max 1 replica (#201)

.github/CODEOWNERS, CODEOWNERS
=> chore: update codeowners (#204)

.github/workflows/anchore.yml
=> chore: fix anchore skip step (#210)

.github/workflows/anchore.yml
=> chore: release prod

Dockerfile
=> fix: IDP-1760 fix new critical CVE-2022-48174 (#213)

src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeApiRetryable.java, src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspect.java, src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryer.java, src/main/java/it/gov/pagopa/common/reactive/mongo/retry/exception/MongoRequestRateTooLargeRetryExpiredException.java, src/main/java/it/gov/pagopa/common/reactive/web/ReactiveRequestContextFilter.java, src/main/java/it/gov/pagopa/common/reactive/web/ReactiveRequestContextHolder.java, src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspectTest.java, src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java, src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryerTest.java
IDP-1765 allow mongo RequestRateTooLarge exception always retryable for selected API
=> feat: IDP-1765 selected API retryable

pom.xml, src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeApiRetryable.java, src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspect.java, src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryer.java, src/main/java/it/gov/pagopa/common/reactive/mongo/retry/exception/MongoRequestRateTooLargeRetryExpiredException.java, src/main/java/it/gov/pagopa/common/reactive/web/ReactiveRequestContextFilter.java, src/main/java/it/gov/pagopa/common/reactive/web/ReactiveRequestContextHolder.java, src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspectTest.java, src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java, src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryerTest.java
=> feat: Release dev

.github/workflows/anchore.yml, Dockerfile, pom.xml, src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeApiRetryable.java, src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspect.java, src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryer.java, src/main/java/it/gov/pagopa/common/reactive/mongo/retry/exception/MongoRequestRateTooLargeRetryExpiredException.java, src/main/java/it/gov/pagopa/common/reactive/web/ReactiveRequestContextFilter.java, src/main/java/it/gov/pagopa/common/reactive/web/ReactiveRequestContextHolder.java, src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspectTest.java, src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java, src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryerTest.java
IDP-1760 fix new critical  CVE-2022-48174
=> feat: Release uat

helm/values.yaml, src/main/java/it/gov/pagopa/reward/connector/repository/HpanInitiativesAtomicOpsRepository.java, src/main/java/it/gov/pagopa/reward/connector/repository/HpanInitiativesAtomicOpsRepositoryImpl.java, src/main/java/it/gov/pagopa/reward/connector/repository/TransactionProcessedAtomicOpsRepository.java, src/main/java/it/gov/pagopa/reward/connector/repository/TransactionProcessedAtomicOpsRepositoryImpl.java, src/main/java/it/gov/pagopa/reward/connector/repository/UserInitiativeCountersAtomicOpsRepository.java, src/main/java/it/gov/pagopa/reward/connector/repository/UserInitiativeCountersAtomicOpsRepositoryImpl.java, src/main/java/it/gov/pagopa/reward/service/commands/ops/DeleteInitiativeService.java, src/main/java/it/gov/pagopa/reward/service/commands/ops/DeleteInitiativeServiceImpl.java, src/main/resources/application.yml, src/test/java/it/gov/pagopa/reward/connector/repository/HpanInitiativesAtomicOpsRepositoryImplTest.java, src/test/java/it/gov/pagopa/reward/connector/repository/TransactionProcessedAtomicOpsRepositoryImplTest.java, src/test/java/it/gov/pagopa/reward/connector/repository/UserInitiativeCountersAtomicOpsRepositoryImplTest.java, src/test/java/it/gov/pagopa/reward/service/commands/ops/DeleteInitiativeServiceImplIntegrationTest.java, src/test/java/it/gov/pagopa/reward/service/commands/ops/DeleteInitiativeServiceImplTest.java
The purpose of this pr is to change the method of deletion from the database from a bulk delete to a paged delete.
- Added find query with batchSize
- Added a single delete for each item to delete/update
- Modified Junit tests
=> fix: IDP-1850-batch-delete

helm/values.yaml, src/main/java/it/gov/pagopa/reward/connector/repository/HpanInitiativesAtomicOpsRepository.java, src/main/java/it/gov/pagopa/reward/connector/repository/HpanInitiativesAtomicOpsRepositoryImpl.java, src/main/java/it/gov/pagopa/reward/connector/repository/TransactionProcessedAtomicOpsRepository.java, src/main/java/it/gov/pagopa/reward/connector/repository/TransactionProcessedAtomicOpsRepositoryImpl.java, src/main/java/it/gov/pagopa/reward/connector/repository/UserInitiativeCountersAtomicOpsRepository.java, src/main/java/it/gov/pagopa/reward/connector/repository/UserInitiativeCountersAtomicOpsRepositoryImpl.java, src/main/java/it/gov/pagopa/reward/service/commands/ops/DeleteInitiativeServiceImpl.java, src/main/resources/application.yml, src/test/java/it/gov/pagopa/reward/connector/repository/HpanInitiativesAtomicOpsRepositoryImplTest.java, src/test/java/it/gov/pagopa/reward/connector/repository/TransactionProcessedAtomicOpsRepositoryImplTest.java, src/test/java/it/gov/pagopa/reward/connector/repository/UserInitiativeCountersAtomicOpsRepositoryImplTest.java, src/test/java/it/gov/pagopa/reward/service/commands/ops/DeleteInitiativeServiceImplIntegrationTest.java, src/test/java/it/gov/pagopa/reward/service/commands/ops/DeleteInitiativeServiceImplTest.java
This PR includes:
- [IDP-1850](https://github.com/pagopa/idpay-reward-calculator/pull/220)
[IDP-1850]: https://pagopa.atlassian.net/browse/IDP-1850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Promote to UAT

helm/values.yaml, src/main/resources/application.yml
The purpose of this PR is to change the pagination value for the delete from 100 to 50
- Changed pageSize value in application.yml and values.yaml
=> fix: IDP-1850-Changed pageSize value in application.yml and values.yaml

pom.xml, src/main/java/it/gov/pagopa/reward/dto/mapper/trx/sync/SynchronousTransactionRequestDTOt2TrxDtoOrResponseMapper.java, src/main/java/it/gov/pagopa/reward/utils/RewardConstants.java, src/test/java/it/gov/pagopa/reward/dto/mapper/trx/sync/SynchronousTransactionRequestDTO2TrxDtoOrResponseMapperTest.java, src/test/java/it/gov/pagopa/reward/service/synchronous/op/CreateTrxSynchronousServiceImplTest.java
Added new channel types for retrieve the instrument who check intervals
- Set instrument
=> feat: refactor retrieve hpan in synchornous flow

src/main/java/it/gov/pagopa/common/reactive/kafka/consumer/BaseKafkaConsumer.java, src/main/java/it/gov/pagopa/reward/service/commands/CommandsMediatorServiceImpl.java, src/test/java/it/gov/pagopa/common/utils/TestUtils.java, src/test/java/it/gov/pagopa/reward/connector/event/consumer/CommandsConsumerConfigTest.java, src/test/java/it/gov/pagopa/reward/connector/event/consumer/HpanInitiaveConsumerConfigTest.java, src/test/java/it/gov/pagopa/reward/connector/event/consumer/RewardRuleConsumerConfigTest.java
=> fix: limiting delete command concurrency

src/main/java/it/gov/pagopa/common/reactive/kafka/consumer/BaseKafkaConsumer.java, src/main/java/it/gov/pagopa/reward/service/build/KieContainerBuilderServiceImpl.java, src/main/java/it/gov/pagopa/reward/service/commands/CommandsMediatorServiceImpl.java, src/main/java/it/gov/pagopa/reward/service/commands/ops/DeleteInitiativeServiceImpl.java, src/test/java/it/gov/pagopa/common/utils/TestUtils.java, src/test/java/it/gov/pagopa/reward/connector/event/consumer/CommandsConsumerConfigTest.java, src/test/java/it/gov/pagopa/reward/connector/event/consumer/HpanInitiaveConsumerConfigTest.java, src/test/java/it/gov/pagopa/reward/connector/event/consumer/RewardRuleConsumerConfigTest.java, src/test/java/it/gov/pagopa/reward/service/commands/ops/DeleteInitiativeServiceImplTest.java
=> fix: limiting CPU usage and reducing concurrency on initiative DELETE

src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspect.java, src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryer.java, src/main/java/it/gov/pagopa/common/reactive/mongo/retry/exception/MongoRequestRateTooLargeRetryExpiredException.java, src/test/java/it/gov/pagopa/common/reactive/mongo/BaseReactiveMongoRepositoryIntegrationTest.java, src/test/java/it/gov/pagopa/common/reactive/mongo/DummySpringRepository.java, src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspectTest.java, src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java, src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryerTest.java, src/test/java/it/gov/pagopa/common/reactive/web/exception/MongoExceptionHandlerTest.java
=> fix: IDP-2003 fix Mongo Retry When Anonymous Repo

.grype.yaml, Dockerfile, pom.xml, src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryer.java, src/main/java/it/gov/pagopa/common/stream/StreamsHealthIndicator.java, src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java, src/main/java/it/gov/pagopa/reward/service/lookup/HpanInitiativeMediatorServiceImpl.java, src/main/java/it/gov/pagopa/reward/service/synchronous/op/CreateTrxSynchronousServiceImpl.java, src/main/resources/application.yml, src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspectTest.java, src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryerTest.java
=> fix: Idp 2016 fix CVE

.github/CODEOWNERS, Dockerfile, src/test/java/it/gov/pagopa/common/mongo/EmbeddedMongodbTestClient.java, src/test/java/it/gov/pagopa/common/mongo/MongoTestIntegrated.java, src/test/java/it/gov/pagopa/common/mongo/singleinstance/AutoConfigureSingleInstanceMongodb.java, src/test/java/it/gov/pagopa/common/mongo/singleinstance/SingleEmbeddedMongodbAutoConfiguration.java, src/test/java/it/gov/pagopa/common/mongo/singleinstance/SingleInstanceMongodWrapper.java, src/test/java/it/gov/pagopa/common/reactive/mongo/BaseReactiveMongoRepositoryIntegrationTest.java, src/test/java/it/gov/pagopa/common/reactive/mongo/BaseReactiveMongoRepositoryTestIntegrated.java, src/test/java/it/gov/pagopa/common/reactive/mongo/EmbeddedMongodbTestReactiveClient.java, src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java, src/test/java/it/gov/pagopa/reward/BaseIntegrationTest.java, src/test/java/it/gov/pagopa/reward/connector/event/processor/UncommittableErrorTest.java, src/test/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, src/test/resources/META-INF/spring/org.springframework.boot.test.autoconfigure.data.mongo.AutoConfigureDataMongo.imports, src/test/resources/mongodbEmbeddedDisabled.properties
=> chore: Release dev

helm/values-uat.yaml, src/main/resources/application.yml, src/test/java/it/gov/pagopa/common/kafka/KafkaTestUtilitiesService.java, src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryerTest.java
Promotion to UAT
- emptying kafka topic at each test + reduced common test timings
- restored KafkaTestUtilitiesService utility method
=> feat: Promote to UAT

src/main/java/it/gov/pagopa/reward/exception/TransactionSynchronousException.java, src/main/java/it/gov/pagopa/reward/service/reward/RewardContextHolderService.java, src/main/java/it/gov/pagopa/reward/service/reward/RewardContextHolderServiceImpl.java, src/main/java/it/gov/pagopa/reward/service/reward/evaluate/InitiativesEvaluatorServiceImpl.java, src/main/java/it/gov/pagopa/reward/service/reward/evaluate/RuleEngineServiceImpl.java, src/main/java/it/gov/pagopa/reward/service/synchronous/op/CreateTrxSynchronousServiceImpl.java, src/main/java/it/gov/pagopa/reward/utils/RewardConstants.java, src/test/java/it/gov/pagopa/reward/connector/event/processor/TransactionProcessorTest.java, src/test/java/it/gov/pagopa/reward/controller/RewardTrxSynchronousApiControllerIntegrationTest.java, src/test/java/it/gov/pagopa/reward/service/reward/RewardContextHolderServiceImplTest.java, src/test/java/it/gov/pagopa/reward/service/reward/evaluate/InitiativesEvaluatorServiceImplTest.java, src/test/java/it/gov/pagopa/reward/service/reward/evaluate/RuleEngineServiceImplTest.java, src/test/java/it/gov/pagopa/reward/service/synchronous/op/CreateTrxSynchronousServiceImplTest.java
=> fix: IDP-2192 kieContainer not ready handling

src/main/java/it/gov/pagopa/common/reactive/mongo/ReactiveMongoRepositoryExt.java, src/main/java/it/gov/pagopa/common/reactive/mongo/ReactiveMongoRepositoryImpl.java, src/main/java/it/gov/pagopa/reward/connector/repository/DroolsRuleRepository.java, src/main/java/it/gov/pagopa/reward/service/build/RewardRuleMediatorServiceImpl.java, src/main/java/it/gov/pagopa/reward/service/commands/ops/DeleteInitiativeServiceImpl.java, src/main/java/it/gov/pagopa/reward/service/reward/RewardContextHolderServiceImpl.java, src/test/java/it/gov/pagopa/reward/connector/event/consumer/CommandsConsumerConfigTest.java, src/test/java/it/gov/pagopa/reward/service/commands/ops/DeleteInitiativeServiceImplTest.java
=> chore: logging drools rules deleted by command

src/main/java/it/gov/pagopa/common/web/exception/ErrorManager.java, src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java, src/main/java/it/gov/pagopa/reward/config/RewardCalculatorErrorManagerConfig.java, src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java, src/test/java/it/gov/pagopa/common/reactive/web/exception/ErrorManagerTest.java, src/test/java/it/gov/pagopa/common/reactive/web/exception/MongoExceptionHandlerTest.java, src/test/java/it/gov/pagopa/reward/controller/InstrumentApiControllerIntegrationTest.java
- Added RewardCalculatorErrorManagerConfig with specifics ErrorDTO
- Update jUnit
=> fix: [IDP-2082] added RewardCalculatorErrorManagerConfig with specifics ErrorDTO

.grype.yaml, Dockerfile, pom.xml, src/test/java/it/gov/pagopa/common/kafka/KafkaTestUtilitiesService.java, src/test/java/it/gov/pagopa/reward/BaseIntegrationTest.java
=> fix: IDP-2196 fix Cve

src/test/java/it/gov/pagopa/reward/connector/event/consumer/CommandsConsumerConfigTestDeprecated.java, src/test/java/it/gov/pagopa/reward/connector/event/consumer/HpanInitiaveConsumerConfigTestDeprecated.java, src/test/java/it/gov/pagopa/reward/connector/event/consumer/RewardRuleConsumerConfigTestDeprecated.java, src/test/java/it/gov/pagopa/reward/connector/event/processor/BaseTransactionProcessorTest.java, src/test/java/it/gov/pagopa/reward/connector/event/processor/TransactionProcessorRefundTestDeprecated.java, src/test/java/it/gov/pagopa/reward/connector/event/processor/TransactionProcessorTestDeprecated.java, src/test/java/it/gov/pagopa/reward/connector/event/processor/UncommittableErrorTest.java, src/test/java/it/gov/pagopa/reward/controller/RewardTrxSynchronousApiControllerIntegrationTest.java, src/test/java/it/gov/pagopa/reward/exception/ErrorManagerExtendedTestDeprecated.java, src/test/java/it/gov/pagopa/reward/service/reward/RewardContextHolderServiceIntegrationTestDeprecated.java
[IDP-2287](https://pagopa.atlassian.net/browse/IDP-2287)
- Rename some tests that extends BaseIntegrationTest to reduce execution time.
[IDP-2287]: https://pagopa.atlassian.net/browse/IDP-2287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [IDP-2287] Changed test class name

src/main/java/it/gov/pagopa/reward/controller/RewardTrxSynchronousApiController.java, src/main/java/it/gov/pagopa/reward/controller/RewardTrxSynchronousApiControllerImpl.java, src/test/java/it/gov/pagopa/reward/controller/RewardTrxSynchronousApiControllerImplTest.java
=> feat: Idp 2278 aggiungere e tag in risposta preview reward calculator

src/main/java/it/gov/pagopa/reward/controller/RewardTrxSynchronousApiController.java, src/main/java/it/gov/pagopa/reward/controller/RewardTrxSynchronousApiControllerImpl.java, src/main/java/it/gov/pagopa/reward/service/synchronous/RewardTrxSynchronousApiService.java, src/main/java/it/gov/pagopa/reward/service/synchronous/RewardTrxSynchronousApiServiceImpl.java, src/main/java/it/gov/pagopa/reward/service/synchronous/op/BaseTrxSynchronousOp.java, src/main/java/it/gov/pagopa/reward/service/synchronous/op/CancelTrxSynchronousService.java, src/main/java/it/gov/pagopa/reward/service/synchronous/op/CancelTrxSynchronousServiceImpl.java, src/main/java/it/gov/pagopa/reward/service/synchronous/op/CreateTrxSynchronousServiceImpl.java, src/test/java/it/gov/pagopa/reward/controller/RewardTrxSynchronousApiControllerImplTest.java, src/test/java/it/gov/pagopa/reward/service/synchronous/op/CancelTrxSynchronousServiceImplTest.java
- restore refund functionality on reward calculator
=> feat: Idp 2357 restore refund functionality on reward calculator

src/main/java/it/gov/pagopa/common/utils/AuditLogger.java, src/test/java/it/gov/pagopa/reward/service/lookup/ops/AddHpanServiceImplTest.java, src/test/java/it/gov/pagopa/reward/service/lookup/ops/DeleteHpanServiceImplTest.java, src/test/java/it/gov/pagopa/reward/test/fakers/HpanInitiativesFaker.java
- fix data time into test and fix auditlogger log
=> chore: Promote to UAT

pom.xml, src/main/java/it/gov/pagopa/reward/connector/repository/UserInitiativeCountersAtomicOpsRepository.java, src/main/java/it/gov/pagopa/reward/connector/repository/UserInitiativeCountersAtomicOpsRepositoryImpl.java, src/main/java/it/gov/pagopa/reward/service/counters/UserInitiativeCountersUnlockMediatorServiceImpl.java, src/main/java/it/gov/pagopa/reward/service/synchronous/op/CancelTrxSynchronousServiceImpl.java, src/main/java/it/gov/pagopa/reward/utils/RewardConstants.java, src/test/java/it/gov/pagopa/reward/connector/repository/UserInitiativeCountersAtomicOpsRepositoryImplTest.java, src/test/java/it/gov/pagopa/reward/service/counters/UserInitiativeCountersUnlockMediatorServiceTest.java
[IDP-2297](https://pagopa.atlassian.net/browse/IDP-2297)
- Added method that handle rollback of counters
[IDP-2297]: https://pagopa.atlassian.net/browse/IDP-2297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [IDP-2297] handle REJECTED rollback

src/main/java/it/gov/pagopa/reward/service/counters/UserInitiativeCountersUnlockMediatorServiceImpl.java, src/test/java/it/gov/pagopa/reward/service/counters/UserInitiativeCountersUnlockMediatorServiceTest.java
- Added optimistic lock for rollback
=> fix: [IDP-2461] Added optimistic lock for rollback synch transaction

src/main/java/it/gov/pagopa/common/kafka/service/ErrorNotifierService.java, src/main/java/it/gov/pagopa/common/kafka/service/ErrorNotifierServiceImpl.java, src/main/java/it/gov/pagopa/common/reactive/kafka/consumer/BaseKafkaBlockingPartitionConsumer.java, src/main/java/it/gov/pagopa/common/reactive/kafka/consumer/BaseKafkaConsumer.java, src/main/java/it/gov/pagopa/common/reactive/mongo/ReactiveMongoRepositoryExt.java, src/main/java/it/gov/pagopa/common/utils/CommonUtilities.java, src/main/java/it/gov/pagopa/common/web/exception/ErrorManager.java, src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java, src/main/java/it/gov/pagopa/common/web/exception/ServiceExceptionHandler.java, src/main/java/it/gov/pagopa/reward/config/KafkaConfiguration.java, src/main/java/it/gov/pagopa/reward/dto/mapper/trx/RewardCountersMapper.java, src/main/java/it/gov/pagopa/reward/model/SrcDetails.java, src/main/java/it/gov/pagopa/reward/service/RewardErrorNotifierService.java, src/main/java/it/gov/pagopa/reward/service/RewardErrorNotifierServiceImpl.java, src/main/java/it/gov/pagopa/reward/service/build/RewardRuleMediatorServiceImpl.java, src/main/java/it/gov/pagopa/reward/service/commands/ops/DeleteInitiativeServiceImpl.java, src/main/java/it/gov/pagopa/reward/service/lookup/HpanInitiativeMediatorServiceImpl.java, src/main/java/it/gov/pagopa/reward/service/reward/RewardCalculatorMediatorServiceImpl.java, src/main/java/it/gov/pagopa/reward/service/synchronous/RewardTrxSynchronousApiServiceImpl.java, src/main/java/it/gov/pagopa/reward/service/synchronous/op/BaseTrxSynchronousOp.java, src/main/java/it/gov/pagopa/reward/service/synchronous/op/CancelTrxSynchronousServiceImpl.java, src/main/java/it/gov/pagopa/reward/service/synchronous/op/CreateTrxSynchronousServiceImpl.java, src/test/java/it/gov/pagopa/common/config/KafkaConfigurationTest.java, src/test/java/it/gov/pagopa/common/kafka/service/ErrorNotifierServiceTest.java, src/test/java/it/gov/pagopa/common/mongo/MongoTestUtilitiesService.java, src/test/java/it/gov/pagopa/reward/service/RewardErrorNotifierServiceTest.java, src/test/java/it/gov/pagopa/reward/service/commands/ops/DeleteInitiativeServiceImplTest.java, src/test/java/it/gov/pagopa/reward/service/synchronous/op/CancelTrxSynchronousServiceImplTest.java
[IDP-2352](https://pagopa.atlassian.net/browse/IDP-2352)
[IDP-2352]: https://pagopa.atlassian.net/browse/IDP-2352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [IDP-2352] Fix code smell and warnings

pom.xml
=> chore: Update pom version

src/main/java/it/gov/pagopa/reward/service/synchronous/op/CancelTrxSynchronousServiceImpl.java, src/main/java/it/gov/pagopa/reward/utils/RewardConstants.java, src/test/java/it/gov/pagopa/reward/service/synchronous/op/CancelTrxSynchronousServiceImplTest.java
- Handle last transactions proccessed into cancel flow
=> feat: Idp 2514 modifica cancellazione gestione idempotenza reward calculator

specs/asyncapi.yaml
=> chore: [IDP-2479] asyncapi documentation

src/main/java/it/gov/pagopa/reward/service/RewardErrorNotifierServiceImpl.java, src/test/java/it/gov/pagopa/reward/service/RewardErrorNotifierServiceTest.java
- Retrieve topic information to be notified in case of an error during HpanInitiative result notifications
=> fix: IDP-2550 initializing fix retrieve topic information to be notified in case of error

.grype.yaml, pom.xml
- Update spring cloud context to fix CVE 
=> chore: fix cve

.github/CODEOWNERS, Dockerfile, pom.xml, src/main/java/it/gov/pagopa/reward/dto/trx/TransactionDTO.java, src/test/java/it/gov/pagopa/reward/dto/mapper/trx/Transaction2RewardTransactionDTOMapperTest.java, src/test/java/it/gov/pagopa/reward/dto/mapper/trx/Transaction2TransactionDroolsMapperTest.java, src/test/java/it/gov/pagopa/reward/dto/mapper/trx/TransactionDrools2RewardTransactionDTOMapperTest.java, src/test/java/it/gov/pagopa/reward/dto/mapper/trx/recover/RecoveredTrx2RewardTransactionMapperTest.java, src/test/java/it/gov/pagopa/reward/dto/mapper/trx/sync/SynchronousTransactionRequestDTO2TrxDtoOrResponseMapperTest.java
=> Release dev

helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml
=> chore:  [IDP-2644] update helm

helm/values-prod.yaml, helm/values-uat.yaml
=> chore: Promote to UAT 

helm/values-prod.yaml, helm/values-uat.yaml
=> chore: promote to Main

.github/workflows/anchore.yml, .github/workflows/flow-docker-snapshot.yml, .github/workflows/release.yml, src/main/java/it/gov/pagopa/common/kafka/utils/KafkaConstants.java
=> chore: add release and snapshot-docker file
